appId: '468866525852336128'
status:
  state: 'Rich presence made by wesselgame'
  detail: 'Github: PassTheWessel/Rich-presence'
  party:
    id: null
    max: 0
    size: 0
  joinSecret: null
  matchSecret: null
  spectateSecret: null
  images:
    small:
      key: 'block_dark'
      text: 'Made by Wesselgame#0498'
    large:
      key: 'block_light'
      text: 'Secret hover text!'
